[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  # Proxy API calls to Render backend; replace BACKEND_URL after deploy
  from = "/api/*"
  to = "https://YOUR-RENDER-SERVICE.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  # SPA fallback
  from = "/*"
  to = "/index.html"
  status = 200


